---
- name: "Refresh services"
  block:
    - systemd:
        state: restarted
        daemon_reload: no
        name: "{{ files.name }}"
      with_items: "{{ systemd_services_to_refresh }}"
      loop_control:
        loop_var: files
  when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0

- name: "Systemd Daemon reload"
  systemd:
    daemon_reload: yes
