---
- ansible.builtin.assert:
    that:
      - nginx_config_dir is defined
      - nginx_config_dir != ""
    quiet: true

- name: "Ensure HTTP cache common config is created"
  ansible.builtin.template:
    src: "{{ config.src }}"
    dest: "{{ config.dest }}"
    owner: "{{ nginx.username }}" 
    group: "{{ nginx.groupname }}"
    mode: 0644
  with_items:
    - { src: templates/commons.d/maven.cache.conf.j2, dest: "{{ nginx_config_dir }}/commons.d/maven.cache.conf" }
    - { src: templates/commons.d/caches.conf.j2, dest: "{{ nginx_config_dir }}/commons.d/caches.conf" }
  loop_control:
    loop_var: config
  notify:
    - restart nginx

- name: "Ensure Maven Central cache directory is created"
  ansible.builtin.file:
    path: "{{ files.directory }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0775
  with_items: "{{ nginx.caches.directories }}"
  loop_control:
    loop_var: files

- name: "Deploy settings.xml to use the caches"
  ansible.builtin.template:
    src: templates/settings.xml.j2
    dest: /opt/tools/settings.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: "Deploy settings-64.xml"
  ansible.builtin.template:
    src: templates/settings-64.xml.j2
    dest: /opt/tools/settings-64.xml
    owner: jenkins
    group: jenkins
    mode: 0644
  when:
    - eap64_caches is defined
