---
- ansible.builtin.assert:
    that:
      - jenkins is defined
      - jenkins.service is defined

- name: "Deploy nginx config for jenkins servers"
  ansible.builtin.template:
    src: templates/commons.d/jenkins.conf.j2
    dest: "{{ nginx_config_dir }}/commons.d/{{ item.name }}.conf"
  loop: "{{ jenkins.service }}"
