---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:

    - name: "Include common prepare tasks"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        users:
          - "{{ user_name }}"
        dirs:
          - { path: "/home/{{ user_name }}", owner: "{{ user_name }}", group: "{{ user_name }}" }
