---
- ansible.builtin.assert:
    that:
      - selinux is defined
      - selinux.state is defined
      - selinux.state != ""
    quiet: true

- ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux.state }}"
