---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: "Include common prepare tasks"
      ansible.builtin.include_tasks: ../prepare.yml

    - ansible.builtin.assert:
        that:
          - jdk_list is defined
          - mvn_list is defined
          - jdk_default is defined
          - jdk_default != ""
          - jdk_default is defined
          - jdk_default_link != ""
          - jdk_default_link is defined
          - mvn_default != ""
          - mvn_default is defined
          - mvn_default_link != ""
          - mvn_default_link is defined
        quiet: true
        fail_msg: "Please check provide variables again."
