---
# dummy variables for java role testing purpose.
jdk_version: 17.0.1
mvn_version: 3.6.3
jdk_home_folder: /opt/java
mvn_home_folder: /opt/java
jdk_list:
  - name: "jdk-{{ jdk_version }}"
    home: "{{ jdk_home_folder }}"
    source: 'https://download.java.net/java/GA/jdk{{ jdk_version }}/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-{{ jdk_version }}_linux-x64_bin.tar.gz'
jdk_default: "{{ jdk_home_folder }}/jdk-{{ jdk_version }}"
jdk_default_link: /opt/java/java_default
mvn_list:
  - name: apache-maven-{{ mvn_version }}
    home: "{{ mvn_home_folder }}"
    source: "https://downloads.apache.org/maven/maven-3/{{ mvn_version }}/binaries/apache-maven-{{ mvn_version }}-bin.tar.gz"
mvn_default: "{{ mvn_home_folder }}/apache-maven-{{ mvn_version }}"
mvn_default_link: /opt/java/mvn_default
yum:
  cache_update : "true"
