---

- assert:
    that:
      - component_alignment is defined
      - component_alignment.home is defined
      - component_alignment.home != ""
      - component_alignment.owner is defined
      - component_alignment.owner != ""
      - component_alignment.group is defined
      - component_alignment.group != ""
      - component_alignment.url is defined
      - component_alignment.path is defined
      - component_alignment.config is defined
      - component_alignment.config.dir is defined
      - mailer is defined
      - mailer.smtp is defined
      - mailer.smtp.host is defined
      - mailer.smtp.port is defined
    quiet: true

- name: "Ensures component alignment home exists: {{ component_alignment.home }}"
  ansible.builtin.file:
    state: directory
    path: "{{ component_alignment.home }}"
    owner: "{{ component_alignment.owner }}"
    group: "{{ component_alignment.group }}"

- name: "Fetch component-alignment jar from {{ component_alignment.url }}"
  ansible.builtin.get_url:
    url: "{{ component_alignment.url }}"
    dest: "{{ component_alignment.path }}"
    owner: "{{ component_alignment.owner }}"
    group: "{{ component_alignment.group }}"
    mode: 0755
  retries: 3
  delay: 5

- name: "Ensure {{ component_alignment.path }} has the appropriate owner, groups and privilege"
  ansible.builtin.file:
    path: "{{ component_alignment.path }}"
    owner: "{{ component_alignment.owner }}"
    group: "{{ component_alignment.group }}"
    mode: 0644

- name: "Create link with stable name to alignment jar"
  ansible.builtin.file:
    src: "{{ component_alignment.path }}"
    dest: "{{ component_alignment_home }}/alignment-cli.jar"
    state: link

- name: "Ensure {{ component_alignment.config.dir }} exists"
  ansible.builtin.file:
    state: directory
    path: "{{ component_alignment.config.dir }}"
    owner: "{{ component_alignment.owner }}"
    group: "{{ component_alignment.group }}"
    mode: 0755

- ansible.builtin.include_tasks: tasks/deploy_config.yml
  with_items: "{{ component_alignment.config.files }}"
  loop_control:
    loop_var: files

- name: "Create component alignment config file"
  ansible.builtin.template:
    src: templates/smtp-settings.sh.j2
    dest: /opt/tools/smtp-settings.sh
    owner: jenkins
    group: jenkins
    mode: 0644
