---
- name: Automate VM with Ansible
  hosts: all
  gather_facts: true
  become: yes

  vars_files:
    - vars/cci.yml
    - vars/java.yml

  pre_tasks:
    - name: Register
      redhat_subscription:
        state: present
        username: "{{ cci_worker_rhel_subscription_username }}"
        password: "{{ cci_worker_rhel_subscription_password }}"
        autosubscribe: yes
        force_register: true

    - name: Update yum
      yum:
        name: "*"
        state: latest

    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: "{{ pretaskfiles }}"
      with_items:
        - firewalld
        - zip
        - podman
        - podman-docker
        - jq
      loop_control:
        loop_var: pretaskfiles

    - name: "Ensure jaegertracing docker image is downloaded for tests"
      containers.podman.podman_image:
        name: "quay.io/jaegertracing/all-in-one:latest"
      become: yes
      become_user: "{{cci_worker_username}}"

  tasks:
    - ansible.builtin.include_role:
        name: "{{ taskfiles }}"
      with_items:
        - cci_worker
        - sshd
        - sudoers
        - ssh
        - java
        - java_certs
        - old_releases
      loop_control:
        loop_var: taskfiles
