---
- name: Automate VM with Ansible
  hosts: all
  gather_facts: true
  become: yes

  vars_files:
    - vars/cci.yml
    - vars/java.yml

  roles:
    - cci_worker
    - sshd
    - sudoers
    - ssh
    - git
    - java
    - java_certs
    - old_releases

  pre_tasks:

    - name: Register
      redhat_subscription:
        state: present
        username: "{{ cci_worker_rhel_subscription_username }}"
        password: "{{ cci_worker_rhel_subscription_password }}"
        autosubscribe: yes

    - name: Update yum
      yum:
        name: "*"
        state: latest

    - include_role:
        name: fast_yum_install
      vars:
        package_name: "{{ item }}"
      with_items:
        - firewalld
        - zip
        - podman

    - name: "Ensure jaegertracing docker image is downloaded for tests"
      containers.podman.podman_image:
        name: "quay.io/jaegertracing/all-in-one:latest"
      become_user: "{{cci_worker_username}}"
