---
- hosts: "{{ hosts_group_name | default('localhost') }}"
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
    - vars/olympus.yml
    - vars/component-alignment.yml
    - vars/aphrodite.yml
    - vars/jobs.yml
    - vars/mailer.yml

  pre_tasks:
    - name: Register
      redhat_subscription:
        state: present
        username: "{{ cci_worker_rhel_subscription_username }}"
        password: "{{ cci_worker_rhel_subscription_password }}"
        autosubscribe: yes
      when:
        - cci_worker_rhel_subscription_password is defined
        - cci_worker_rhel_subscription_username is defined

    - name: Update yum
      yum:
        name: "*"
        state: latest

    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: "{{ item }}"
      with_items:
        - firewalld
        - zip

  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      with_items:
        - old_releases
        - component_alignment
        - pr_processor
        - aphrodite
