---
- hosts: "{{ hosts_group_name | default('localhost') }}"
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
    - vars/vault.yml
    - vars/olympus.yml
    - vars/component-alignment.yml
    - vars/aphrodite.yml
    - vars/jobs.yml
    - vars/mailer.yml

  pre_tasks:
    - name: "Install hvac python library"
      ansible.builtin.pip:
        name: hvac>=1.2.1
        executable: pip3

    - name: "Load Secrets from Vault"
      ansible.builtin.include_role:
        name: "vault"

    - name: Register
      redhat_subscription:
        state: present
        username: "{{ cci_worker_rhel_subscription_username }}"
        password: "{{ cci_worker_rhel_subscription_password }}"
        autosubscribe: yes
      when:
        - cci_worker_rhel_subscription_password is defined
        - cci_worker_rhel_subscription_username is defined

    - name: Update yum
      yum:
        name: "*"
        state: latest

    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: "{{ pretaskfiles }}"
      with_items:
        - firewalld
        - zip
      loop_control:
        loop_var: pretaskfiles

  tasks:
    - ansible.builtin.include_role:
        name: "{{ taskfiles }}"
      with_items:
        - old_releases
        - component_alignment
        - pr_processor
        - aphrodite
      loop_control:
        loop_var: taskfiles
