---
- name: "Determine filename for secrets."
  ansible.builtin.set_fact:
    secrets_filename: "{{ override_secrets_filename  | default('/etc/ansible/secrets.yml') }}"

- name: "Load metadata from secrets file ({{ secrets_filename }})."
    ansible.builtin.stat:
    path: "{{ secrets_filename }}"
  register: secrets

- name: "Load secrets from {{ secrets_filename }}"
  include_vars: "{{ secrets_filename }}"
  when:
    - secrets.stat.exists
    - ansible_hostname != 'olympus'
