---
- hosts: localhost
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
      - vars/vault.yml
      - vars/ansible.yml
      - vars/olympus.yml
      - vars/ssh.yml
      - vars/aphrodite.yml
      - vars/netrc.yml
      - vars/monit.yml
      - vars/caches.yml
      - vars/java.yml
      - vars/java_certs.yml
      - vars/jenkins_sso.yml
      - vars/jobs.yml
      - vars/component-alignment.yml
      - vars/mailer.yml
      - vars/ldap.yml
      - vars/pgsql.yml
      - vars/hosts.yml
      - vars/qualys.yml

  pre_tasks:
    - name: "Install hvac python library"
      ansible.builtin.pip:
        name: hvac>=1.2.1
        executable: pip3

    - name: "Load Secrets from Vault"
      ansible.builtin.include_role:
        name: "vault"

    - name: Register
      community.general.redhat_subscription:
        state: present
        username: "{{ cci_worker_rhel_subscription_username }}"
        password: "{{ cci_worker_rhel_subscription_password }}"
        autosubscribe: yes
      when:
        - cci_worker_rhel_subscription_username is defined
        - cci_worker_rhel_subscription_password is defined

    - ansible.builtin.include_role:
        name: qualys_fix
    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: python3-pyOpenSSL.noarch

    - ansible.builtin.set_fact:
        secrets_filename: "{{ override_secrets_filename  | default('/etc/ansible/secrets.yml') }}"

    - ansible.builtin.stat:
        path: "{{ secrets_filename }}"
      register: secrets

    - name: "Load secrets"
      include_vars: "{{ secrets_filename }}"
      when:
        - secrets.stat.exists
        - ansible_hostname != 'olympus'

    - ansible.builtin.hostname:
        name: "{{ ansible_hostname }}"

    - ansible.builtin.include_role:
        name: account
      vars:
        account:
          username: "{{ jenkins_name }}"
          uid: "{{ jenkins_uid }}"
          group: "{{ jenkins_group }}"
          gid: "{{ jenkins_gid }}"
          home: "{{ jenkins_home | default('/home/jenkins') }}"

    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: firewalld

    - ansible.builtin.include_role:
        name: "{{ pretaskfiles }}"
      with_items:
        # OS settings and optimizations
        - selinux
        - motd
        - bashrc
        - kdump
        - sysctl
        - tuned
        - hosts
        - netrc
        - git
        - ansible
        - ssh
      loop_control:
        loop_var: pretaskfiles

  tasks:
    - ansible.builtin.include_role:
        name: "{{ taskfiles }}"
      with_items:
        # main services
        - sshd
        - ares
        - java
        - pgsql
        - jenkins
        - nginx
        - podman
        - systemd
        - java_certs
        - payload_status
      loop_control:
        loop_var: taskfiles

  post_tasks:
    - ansible.builtin.include_role:
        name: "{{ posttaskfiles }}"
      with_items:
        - monit
        #- cron # disabled because the only item is the Ansible daily run which are currently disable (Vault)
        - infosec.qualys-cloud-agent
      loop_control:
        loop_var: posttaskfiles

- ansible.builtin.import_playbook: jenkins.yml
