---
- hosts: "{{ hosts_group_name | default('localhost') }}"
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
      - vars/olympus.yml
      - vars/ssh.yml
      - vars/aphrodite.yml
      - vars/netrc.yml
      - vars/monit.yml
      - vars/caches.yml
      - vars/java.yml
      - vars/java_certs.yml
      - vars/jobs.yml
      - vars/component-alignment.yml
      - vars/mjolnir.yml
      - vars/mailer.yml
      - vars/ldap.yml
      - vars/pgsql.yml
      - vars/hosts.yml
      - vars/qualys.yml

  pre_tasks:
    - name: Register
      community.general.redhat_subscription:
          state: present
          username: "{{ cci_worker_rhel_subscription_username }}"
          password: "{{ cci_worker_rhel_subscription_password }}"
          autosubscribe: yes
      when:
        - cci_worker_rhel_subscription_username is defined
        - cci_worker_rhel_subscription_password is defined

    - set_fact:
        secrets_filename: "{{ override_secrets_filename  | default('/etc/ansible/secrets.yml') }}"

    - stat:
        path: "{{ secrets_filename }}"
      register: secrets

    - name: "Load secrets"
      include_vars: "{{ secrets_filename }}"
      when:
        - secrets.stat.exists
        - ansible_hostname != 'olympus'

    - hostname:
        name: "{{ ansible_hostname }}"

    - include_role:
        name: account
      vars:
        account:
          username: "{{ jenkins_name }}"
          uid: "{{ jenkins_uid }}"
          group: "{{ jenkins_group }}"
          gid: "{{ jenkins_gid }}"
          home: "{{ jenkins_home | default('/home/jenkins') }}"

    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: firewalld

    - ansible.builtin.include_role:
        name: "{{ item }}"
      with_items:
        # OS settings and optimizations
        - selinux
        - motd
        - bashrc
        - kdump
        - sysctl
        - tuned
        - hosts

  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      with_items:
        # main services
        - git
        - sshd
        - ssh
        - ares
        - java
        - jenkins
        - pgsql
        - nginx
        - podman
        - systemd
        - java_certs
        # auth and sudoers.yml
        - netrc

  post_tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      with_items:
        # monitoring
        - monit
        - cron
        - infosec.qualys-cloud-agent

- ansible.builtin.import_playbook: jenkins.yml

