---
- hosts: "{{ hosts_group_name | default('localhost') }}"
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
      - vars/olympus.yml
      - vars/ssh.yml
      - vars/aphrodite.yml
      - vars/netrc.yml
      - vars/monit.yml
      - vars/caches.yml
      - vars/java.yml
      - vars/java_certs.yml
      - vars/jobs.yml
      - vars/component-alignment.yml
      - vars/mjolnir.yml
      - vars/mailer.yml
      - vars/ldap.yml
      - vars/pgsql.yml
      - vars/hosts.yml
      - vars/qualys.yml
  roles:
    # stage 1 - OS settings and optimizations
    - selinux
    - motd
    - bashrc
    - kdump
    - sysctl
    - tuned
    - hosts
    # stage 2 - main services
    - git
    - sshd
    - ssh
    - ares
    - java
    - jenkins
    - pgsql
    - nginx
    - old_releases
    - podman
    - systemd
    - java_certs
    - payload_status
    # stage 3 - auth and sudoers.yml
    - component_alignment
    - pr_processor
    - aphrodite
    - netrc
    # monitoring
    - monit
    - cron
    - infosec.qualys-cloud-agent
  pre_tasks:
    - ansible.builtin.include_role:
        name: qualys_fix
    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: python3-pyOpenSSL.noarch

    - set_fact:
        secrets_filename: "{{ override_secrets_filename  | default('/etc/ansible/secrets.yml') }}"

    - stat:
        path: "{{ secrets_filename }}"
      register: secrets

    - name: "Load secrets"
      include_vars: "{{ secrets_filename }}"
      when:
        - secrets.stat.exists
        - ansible_hostname != 'olympus'

    - hostname:
        name: "{{ ansible_hostname }}"

    - include_role:
        name: account
      vars:
        account:
          username: "{{ jenkins_name }}"
          uid: "{{ jenkins_uid }}"
          group: "{{ jenkins_group }}"
          gid: "{{ jenkins_gid }}"
          home: "{{ jenkins_home | default('/home/jenkins') }}"

    - include_role:
        name: fast_yum_install
      vars:
        package_name: firewalld
