---
- ansible.builtin.assert:
    that:
      - certificate_list is defined
      - certificate_list is iterable

# reset cacerts_file fact between iterations
- ansible.builtin.set_fact:
    cacerts_file: ''

# determine the location of cacerts file
- ansible.builtin.stat:
    path: "{{ jdk.home }}/{{ jdk.name }}/jre/lib/security/cacerts"
  register: cacerts_file_stat

- ansible.builtin.set_fact:
    cacerts_file: "{{ jdk.home }}/{{ jdk.name }}/jre/lib/security/cacerts"
  when: cacerts_file_stat.stat.exists

- ansible.builtin.stat:
    path: "{{ jdk.home }}/{{ jdk.name }}/lib/security/cacerts"
  register: cacerts_file_stat_alt
  when: cacerts_file == ''

- ansible.builtin.set_fact:
    cacerts_file: "{{ jdk.home }}/{{ jdk.name }}/lib/security/cacerts"
  when:
    - (not cacerts_file_stat is defined) or (not cacerts_file_stat.stat.exists)
    - cacerts_file_stat_alt.stat.exists

- ansible.builtin.assert:
    that:
      cacerts_file is defined

- name: Remove Root CA  in {{ jdk.name }}
  when: rebuild_keystore|default(false)
  community.general.java_cert:
    cert_path: "{{ jdk_home }}/Root-CA.crt"
    keystore_path: "{{ cacerts_file }}"
    cert_alias: "internal.redhat.com"
    executable: "{{ jdk.home }}/{{ jdk.name }}/bin/keytool"
    keystore_pass: changeit
    keystore_create: no
    state: absent

- name: Remove SSL certificates in {{ jdk.name }}
  when: rebuild_keystore|default(false)
  community.general.java_cert:
    cert_url: "{{ removessl.cert_url }}"
    keystore_path: "{{ cacerts_file }}"
    cert_alias: "{{ removessl.alias }}"
    executable: "{{ jdk.home }}/{{ jdk.name }}/bin/keytool"
    keystore_pass: changeit
    keystore_create: no
    state: absent
  with_items: "{{ certificate_list }}"
  loop_control:
    loop_var: removessl

- name: Import Root CA in {{ jdk.name }} {{ cacerts_file }}
  community.general.java_cert:
    cert_path: "{{ jdk_home }}/Root-CA.crt"
    keystore_path: "{{ cacerts_file }}"
    cert_alias: "internal.redhat.com"
    executable: "{{ jdk.home }}/{{ jdk.name }}/bin/keytool"
    keystore_pass: changeit
    keystore_create: no
    state: present

- name: Import SSL certificates in {{ jdk.name }}
  community.general.java_cert:
    cert_url: "{{ importssl.cert_url }}"
    keystore_path: "{{ cacerts_file }}"
    cert_alias: "{{ importssl.alias }}"
    executable: "{{ jdk.home }}/{{ jdk.name }}/bin/keytool"
    keystore_pass: changeit
    keystore_create: no
    state: present
  with_items: "{{ certificate_list }}"
  loop_control:
    loop_var: importssl
