---
- assert:
    that:
      - jdk_list is defined 
      - jdk_list is iterable

- name: "Provisioning self-signed certificate to JDKs"
  include_tasks: tasks/java_certs.yml
  loop: "{{ jdk_list }}"
  loop_control:
    loop_var: jdk
