---
- ansible.builtin.assert:
    that:
      - monit is defined
      - monit.alerts is defined
      - monit.alerts.disk_usage is defined
      - (monit.alerts.disk_usage | length ) > 0
    quiet: true

- name: "Set up Monit alert on disk usage"
  ansible.builtin.template:
    src: templates/monit.disk.j2
    dest: "/etc/monit.d/{{ files.name }}"
  notify:
    - restart monit
  with_items: "{{ monit.alerts.disk_usage }}"
  loop_control:
    loop_var: files
