---
- ansible.builtin.include_tasks: setup.yml

- ansible.builtin.include_tasks: config_mail.yml
  when: monit.email is defined

- ansible.builtin.include_tasks: system_alerts.yml
  when: monit.alerts.system is defined

- ansible.builtin.include_tasks: dns_alerts.yml
  when: monit.alerts.dnsnames is defined

- ansible.builtin.include_tasks: disk_usage_alerts.yml
  when: monit.alerts.disk_usage is defined

- name: "Ensures custom scripts folder exists"
  ansible.builtin.file:
    path: "{{ monit_custom_scripts_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0655
  when:
    - monit_custom_scripts_directory is defined
    - monit.alerts.custom_scripts is defined

- ansible.builtin.include_tasks: custom_alerts.yml
  when:
    - monit is defined and monit.alerts is defined
    - monit.alerts.custom_scripts is defined
    - monit.alerts.custom_scripts | length > 0
  with_items: "{{ monit.alerts.custom_scripts }}"
  loop_control:
    loop_var: alerts

- ansible.builtin.include_tasks: services_alerts.yml
  when: monit.alerts.services is defined
