---
- include_tasks: setup.yml

- include_tasks: config_mail.yml
  when: monit.email is defined

- include_tasks: dns_alerts.yml
  when: monit.alerts.dnsnames is defined

- include_tasks: disk_usage_alerts.yml
  when: monit.alerts.disk_usage is defined

- include_tasks: custom_alerts.yml
  when: monit.alerts.custom_scripts is defined

- include_tasks: services_alerts.yml
  when: monit.alerts.services is defined
