---
- ansible.builtin.assert:
    that:
      - monit is defined
      - monit.alerts is defined
      - monit.alerts.services is defined
      - (monit.alerts.services | length) > 0
    quiet: true

- name: "Ensure required services are running under Monit control"
  ansible.builtin.template:
    src: templates/monit.service.j2
    dest: "/etc/monit.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0755
  notify:
    - restart monit
  with_items: "{{ monit.alerts.services }}"
