---

- ansible.builtin.stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_path

- ansible.builtin.assert:
    that:
      - epel_path is defined
      - epel_path.stat is defined
    quiet: true

- name: "Ensures EPEL repo are installed: {{ vpn.epel.url }}"
  ansible.builtin.yum:
    name: "{{ epel.url }}"
    disable_gpg_check: yes
    state: present
  when:
    - not epel_path.stat.exists

- ansible.builtin.include_role:
    name: fast_yum_install
  vars:
    package_name: NetworkManager-openvpn


- ansible.builtin.include_role:
    name: fast_yum_install
  vars:
    package_name: monit

- ansible.builtin.assert:
    that:
      - monit is defined
      - monit.daemon is defined
      - (monit.daemon | int) > 0
    quiet: true
    fail_msg: "Invalid Monit configuration"

- name: "Deploy Monit main config"
  ansible.builtin.template:
    src: templates/monitrc.j2
    dest: /etc/monitrc
    mode: 0700
    owner: root
    group: root
  notify:
    - restart monit
- name: "Ensures monit.conf.d is properly created and set"
  ansible.builtin.file:
    state: directory
    path: /etc/monit.d/
    owner: root
    group: root

- ansible.posix.firewalld:
    port: "{{ monit.webapp.port}}/tcp"
    permanent: yes
    state: enabled
  when:
    - monit.webapp is defined
    - monit.webapp.port is defined
    - (monit.webapp.port | int) > 0

- ansible.builtin.service:
    name: monit
    state: started
    enabled: yes
  when:
    - local_dev_env is not defined
