---
- name: Verify for fast_yum_install role
  hosts: localhost
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
    - name: Check fast_yum_install role is working.
      ansible.builtin.command: "nginx -v"
      register: nginx_result

    - ansible.builtin.debug:
        msg: "fast_yum_install role is not working."
      when: nginx_result is failed