---
- name: "Generate configfile for jobs"
  template:
    src: templates/component-alignment-config-template.csv.j2
    dest: "/opt/tools/component-alignment-config-template.csv"
    owner: jenkins
    group: jenkins
    mode: 0644
  when:
    - component_alignment is defined
    - component_alignment.jobs is defined

