- set_fact:
    package_name: "{{ jboss.package_name }}"

# Skip EAP configuration to prevent EAP from starting - remove if needs to run EAP
- set_fact:
    skip_eap_configuration: "true"

- name: "Ensures jboss-eap7 RPM package is installed"
  import_tasks: tasks/rpminfo.yml

- name: "Deploy SystemD configuratuon for jboss-eap7"
  template:
    src: templates/eap7-standalone.service.j2
    dest: /usr/lib/systemd/system/eap7-standalone.service
    group: root
    owner: root

- name: "Deploy configuration for jboss-eap7"
  template:
    src: templates/eap7-standalone.conf.j2
    dest: /etc/opt/rh/eap7/wildfly/eap7-standalone.conf
    group: jboss
    owner: jboss

- name: "Ensure JBoss EAP 7 is running"
  service:
    name: 'eap7-standalone'
    state: stopped
    enabled: no

- name: "Wait for EAP7 to start"
  wait_for:
    timeout: 5
  delegate_to: localhost
  when: skip_eap_configuration is not defined or skip_eap_configuration == 'false'

- name: "Tuning Wildfly using JCliff (CLI running on port {{ 9990 + jboss.port_shift|int }})"
  jcliff:
    wfly_home: /opt/rh/eap7/root/usr/share/wildfly/
    management_port: "{{ jboss.port_shift|int + 9990 }}"
    timeout: 5000000
    subsystems:
      - system_props:
        - name: jcliff.enabled
          value: true
        - name: aphrodite.config
          value: /home/jboss/prbz-overview/aphrodite.properties.json
        - name: payload.properties
          value: /home/jboss/prbz-overview/payload.properties
        - name: cacheDir
          value: /home/jboss/cache
        - name: cacheName
          value: github-cache
        - name: cacheSize
          value: 20
        - name: java.util.logging.manager
          value: org.jboss.logmanager.LogManager
      - interfaces:
        - name: management
          inet_address: "{{ jboss.management_addr }}"
        - name: public
          inet_address: "{{ jboss.bind_addr }}"
        - name: internal
          inet_address: "{{ jboss.management_addr }}"
      - standard_sockets:
          socket_binding:
            - name: http
              interface: public
              port: "8080"
            - name: https
              interface: public
              port: "8443"
            - name: management-http
              interface: internal
              port: "9990"
            - name: management-https
              interface: internal
              port: "9993"
            - name: txn-recovery-environment
              interface: internal
              port: "4712"
            - name: txn-status-manager
              interface: internal
              port: "4713"
  when: skip_eap_configuration is not defined or skip_eap_configuration == 'false'
