- set_fact: package_name=nginx
- name: "Install nginx packages"
  import_tasks: tasks/rpminfo.yml

- name: "Ensure folder for common configurations is created"
  file:
    path: /etc/nginx/commons.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: "Ensure HTTP cache common config is created"
  template:
    src: templates/nginx.maven.cache.conf.j2
    dest: /etc/nginx/commons.d/nginx.maven.cache.conf
    owner: root
    group: root
    mode: 0775

- name: "Deploy nginx common proxy settings"
  template:
    src: templates/nginx.proxy.j2
    dest: /etc/nginx/proxy.conf
    owner: root
    group: root
    mode: '0644'

- name: "Ensure Maven Central cache directory is created"
  file:
    path: "{{ maven_http_cache_common_config.directory }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0775

- name: "Deploy credentials for monit app"
  template:
    src: templates/nginx.monit.passwd.j2
    dest: /etc/nginx/monit.passwd

- name: "Deploy nginx configuration"
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644

- name: "Deploy custom 404 page for Nginx"
  template:
    src: templates/jboss-set-404.html.j2
    dest: /usr/share/nginx/html/jboss-set-404.html
    owner: root
    group: root

- name: "Ensure nginx is running"
  service:
    name: nginx
    state: started
    enabled: yes
