---
- name: "Podman based services under Systemd control:"
  ansible.builtin.debug:
    msg: "- {{ item.name }}"
  loop: "{{ podman_services }}"

- ansible.builtin.include_tasks: podman.yml
  loop: "{{ podman_services }}"

- name: "Following services needs to be refreshed"
  ansible.builtin.debug:
    msg: "{{ item.name }}"
  loop: "{{ systemd_services_to_refresh }}"
  when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0
  changed_when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0
  notify: "Refresh services"

- name: "Ensures podman_services are running"
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: "{{ item.state | default('started') }}"
    enabled: yes
  loop: "{{ podman_services }}"
