---
- name: "Podman based services under Systemd control"
  ansible.builtin.debug:
    msg: "- {{ podman_service.name }}"
  with_items: "{{ podman_services }}"
  loop_control:
    loop_var: podman_service

- ansible.builtin.include_tasks: podman.yml
  with_items: "{{ podman_services }}"
  loop_control:
    loop_var: podman_service

- name: "Following services needs to be refreshed"
  ansible.builtin.debug:
    msg: "{{ service.name }}"
  with_items: "{{ systemd_services_to_refresh }}"
  loop_control:
    loop_var: service
  when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0
  changed_when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0
  notify: "Refresh services"

- name: "Ensures podman_services are running"
  ansible.builtin.service:
    name: "{{ podman_service.name }}"
    state: "{{ podman_service.state | default('started') }}"
    enabled: "{{ podman_service.enable | default('yes') }}"
  with_items: "{{ podman_services }}"
  loop_control:
    loop_var: podman_service
