---
- name: "Podman based services under Systemd control:"
  ansible.builtin.debug:
    msg: "- {{ services.name }}"
  with_items: "{{ podman_services }}"
  loop_control:
    loop_var: services

- ansible.builtin.include_tasks: podman.yml
  with_items: "{{ podman_services }}"
  loop_control:
    loop_var: files

- name: "Following services needs to be refreshed"
  ansible.builtin.debug:
    msg: "{{ services.name }}"
  with_items: "{{ systemd_services_to_refresh }}"
  loop_control:
    loop_var: services
  when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0
  changed_when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0
  notify: "Refresh services"

- name: "Ensures podman_services are running"
  ansible.builtin.service:
    name: "{{ services.name }}"
    state: "{{ services.state | default('started') }}"
    enabled: yes
  with_items: "{{ podman_services }}"
  loop_control:
    loop_var: services
