---
- ansible.builtin.assert:
    that: 
      - podman_service is defined
      - podman_service.name is defined
      - podman_home is defined
    quiet: yes

- name: "Deploy service script for podman based systemd service called {{ podman_service.name }}"
  ansible.builtin.template:
    src: templates/service-settings.sh.j2
    dest: "{{ podman_home}}/{{ podman_service.name }}.config.sh"
    owner: root
    group: root
    mode: 0755

- name: "Deploy systemd config for service"
  ansible.builtin.template:
    src: templates/systemd.podman.config.j2
    dest: "/usr/lib/systemd/system/{{ podman_service.name }}.service"
    owner: root
    group: root
    mode: 0755
  notify:
    - Systemd Daemon reload

- name: "Create symlink for service"
  ansible.builtin.file:
    src: "{{ podman_home }}/podman-service.sh"
    dest: "{{ podman_home }}/{{ podman_service.name }}-service.sh"
    owner: root
    group: root
    state: link
