---
- name: Verify for kdump role
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
    - name: Add a duplicate kdump configuration
      ansible.builtin.template:
        src: "../../roles/kdump/templates/kdump.j2"
        dest: /etc/duplicateKdump.conf
        owner: root
        group: root
        mode: 0644

    - name: Get checksum of my original file
      ansible.builtin.stat:
        path: "/etc/kdump.conf"
      register: originalfile

    - ansible.builtin.set_fact:
        original: "{{ originalfile.stat.checksum }}"

    - name: Get checksum of my duplicate file
      ansible.builtin.stat:
        path: "/etc/duplicateKdump.conf"
      register: duplicatefile

    - ansible.builtin.set_fact:
        duplicate: "{{ duplicatefile.stat.checksum }}"

    - name: Compare both the kdump configuration files
      ansible.builtin.debug:
        msg: "File Compare"
      failed_when: original != duplicate

    - name: Verify that kdump role was properly executed
      ansible.builtin.assert:
        that: true
