---
- ansible.builtin.assert:
    that:
      - files is defined
    quiet: true

- ansible.builtin.include_tasks: deploy/db.yml
  vars:
    script: "{{ files.create_db }}"
    dest: "{{ pgsql.scripts.home }}/{{ files.create_db.name }}"
    db_info: "{{ files }}"
  when: 
    - files.create_db is defined
    - files.create_db.name is defined

- ansible.builtin.include_tasks: deploy/db.yml
  vars:
    script: "{{ files.load_data }}"
    dest: "{{ pgsql.scripts.home }}/{{ files.load_data.name }}"
    db_info: "{{ files }}"
  when:
    - files.load_data is defined
    - files.load_data.name is defined
