---
- ansible.builtin.assert:
    that: 
      - sql_script_to_run is defined
      - sql_script_to_run | length > 0

- ansible.builtin.debug:
    msg: "{{ sql_script_to_run }}"

- community.postgresql.postgresql_query:
    db: "{{ files.instance.db_name }}"
    path_to_script: "{{ files.path }}"
    login_host: localhost
    port: "{{ files.instance.port }}"
    login_user: "{{ files.instance.username }}"
    login_password: "{{ files.instance.password }}"
  with_items: "{{ sql_script_to_run }}"
  loop_control:
    loop_var: files

