---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:

    - name: "Include common prepare tasks"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        users:
          - "{{ git_user }}"
        dirs:
          - { path: /home/jenkins, owner: "{{ git_user }}", group: "{{ git_user }}" }
