---
- name: Prepare
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Add the user jenkins
      ansible.builtin.user:
        name: jenkins
    - name: Creates directory
      ansible.builtin.file:
        path: /home/jenkins
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0644
