---
- name: Verify for motd role
  hosts: all
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
    - name: Check if Git is installed.
      ansible.builtin.command: "git --version"
      register: git_result

    - ansible.builtin.debug:
        msg: "Git is not installed."
      when: git_result is failed
