---
- ansible.builtin.assert:
    that:
      - cronjobs is defined
      - cronjobs | length > 0

- ansible.builtin.include_role:
    name: fast_yum_install
  vars:
    package_name: "{{ item }}"
  loop:
    - mailx
    - cronie

- ansible.builtin.include_tasks: cronjob.yml
  loop: "{{ cronjobs }}"
