---
- ansible.builtin.assert:
    that:
      - cronjobs is defined
      - cronjobs | length > 0

- ansible.builtin.include_role:
    name: fast_yum_install
  vars:
    package_name: "{{ files }}"
  with_items:
    - mailx
    - cronie
  loop_control:
    loop_var: files

- ansible.builtin.include_tasks: cronjob.yml
  with_items: "{{ cronjobs }}"
  loop_control:
    loop_var: jobs
