---
- name: Verify for cron role
  hosts: all
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
  - name: Removes cron tasks
    ansible.builtin.cron:
      name: "{{ files.name }}"
      user: root
      state: absent
    with_items: "{{ cronjobs }}"
    loop_control:
      loop_var: files
