---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: "Include common prepare tasks"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        dirs:
          - { path: /etc/fake_hosts, state: touch, mode: 0644 }
          - { path: /etc/real_hosts, state: touch, mode: 0644 }

    - name: "Include fast_yum_install"
      ansible.builtin.include_role:
        name: "fast_yum_install"
