---
- ansible.builtin.assert:
    that:
      - script is defined
      - script.name is defined
      - script.name | length > 0 
      - dest is defined
    quiet: true

- name: "Ensures {{ script.name }} exists."
  ansible.builtin.template:
    src: "{{ script.name }}.j2"
    dest: "{{ dest }}"
    force: "yes"
  register: script_template_execution
  when:
    - script.url is not defined
  notify: run sql init scripts

- name: "Ensures {{ script.name }} exists (source: {{ script.url }}."
  ansible.builtin.get_url:
    url: "{{ script.url }}"
    dest: "{{ dest }}"
    force: "yes"
  register: script_geturl_execution
  when: 
    - script.url is defined
    - not ansible_check_mode
  notify: run sql init scripts
