---
- name: Prepare
  hosts: all
  gather_facts: yes
  tasks:

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "Install sudo if user is root"
      ansible.builtin.yum:
        name: sudo
        state: present
      when:
        - ansible_user_id == "root"
