---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Test source profile
      ansible.builtin.shell: source /etc/bashrc
      register: func_result

    - name: check result
      ansible.builtin.debug:
        var: func_result.stdout