---
- ansible.builtin.set_fact:
    yum_module_name: container-tools

- name: "Check if {{ yum_module_name }}"
  ansible.builtin.command: >
    yum module list --installed  {{ yum_module_name }}
  args:
    warn: false
  register: is_yum_module_installed
  ignore_errors: yes
  changed_when: false

- name: "Install yum module for Podman"
  ansible.builtin.command: >
    yum module install -y container-tools
  when:
    - is_yum_module_installed is defined
    - is_yum_module_installed.rc is defined
    - is_yum_module_installed.rc

- ansible.builtin.include_role:
    name: fast_yum_install
  vars:
    package_name: "{{ files }}"
  with_items: "{{ podman.packages }}"
  loop_control:
    loop_var: files

- name: "Ensure user namespaces has been increased"
  ansible.builtin.template:
    src: templates/userns.conf.j2
    dest: "{{ podman.kernel.user_namespaces_config_file }}"
  notify:
    - sysctl-userns

- name: "Ensure podman service is running"
  ansible.builtin.service:
    name: "{{ service.name }}"
    state: "{{ service.state }}"
    enabled: "{{ service.enabled }}"
  with_items:
    - { name: podman.socket, enabled: yes, state: started }
    - { name: podman, enabled: yes, state: stopped }
      #    - { name: podman.slice, enabled: yes, state: stopped }
  loop_control:
    loop_var: service

- name: "Ensures jenkins can use podman"
  ansible.builtin.command: loginctl enable-linger jenkins
  changed_when: false

- name: "Ensures any user can access podman keys (podman pull)"
  ansible.builtin.file:
    dest: /etc/docker/certs.d/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    recurse: yes
