---
- assert:
    that:
      - account is defined
      - account.username is defined
      - account.username != ""
      - account.password is defined
      - account.password != ""
      - account.home is defined
    quiet: true

- name: "Creating {{ account.username }} user."
  user:
    name: "{{ account.username }}"
    state: present
    password: "{{ account.password | password_hash('sha512', 'A512') }}"
    shell: /bin/bash

- name: "Ensure path provided for home is valid"
  stat:
    path: "{{ account.home }}"
  register: account_home

- name: "Ensure home directory {{ account.home }} exists."
  file:
    state: directory
    path: "{{ account.home }}"
    owner: "{{ account.username }}"
  when: account_home.stat is defined

- name: "Ensure ssh directory for {{ account.username }} exists"
  file:
    state: directory
    path: "{{ account.home }}/.ssh"
    owner: "{{ account.username }}"

- name: "Deploy authorized key"
  authorized_key:
    user: "{{ account.username }}"
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ account.pubkey_file }}"

- name: "Deploy fix_multicast script"
  copy:
    src: "files/setup_multicast.sh"
    dest: "/usr/local/sbin/setup_multicast.sh"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Create boot-time service to fix multicast"
  copy:
    src: "files/setup_multicast.service"
    dest: "/etc/systemd/system/setup_multicast.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Ensures setup_multicast service is running"
  service:
    name: "setup_multicast.service"
    state: started
    enabled: yes