---
- ansible.builtin.include_role:
    name: fast_yum_install
  vars:
    package_name: git
  
- name: "Ensures gitconfig is deployed for user root"
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: "{{ config.home }}/.gitconfig"
    owner: "{{ config.user }}"
    group: "{{ config.user }}"
    mode: u=rw,g=r,o=r
  with_items: "{{ git.users }}"
  loop_control:
    loop_var: config
