---
- name: Verify for account role
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
    - name: "Ensure group {{ account.group }} exists."
      ansible.builtin.group:
        name: "{{ account.group }}"
        gid: "{{ account.gid }}"
        state: present
      register: group_result

    - name: "Check that group already existed"
      ansible.builtin.assert:
        that:
          - group_result is not changed
        fail_msg: "{{ account.group }} doesn’t exist."

    - name: "Ensure user {{ account.username }} exists."
      ansible.builtin.user:
        name: "{{ account.username }}"
        uid: "{{ account.uid }}"
        group: "{{ account.group }}"
        state: present
      register: user_result

    - name: "Check that user already existed."
      ansible.builtin.assert:
        that:
          - user_result is not changed
        fail_msg: "{{ account.username }} doesn’t exist."
