---
- ansible.builtin.assert:
    that:
      - home_folder is defined
      - home_folder != ""
      - files is defined
      - files.name is defined
      - files.name != ""
      - files.source is defined
      - files.source != ""
    quiet: true

- ansible.builtin.set_fact:
    path_to_archive: "{{ home_folder }}/{{ files.name }}{{ files.ext | default('.tgz') }}"

- name: "Escalate priviliges"
  block:
    - ansible.builtin.stat:
        path: "{{ path_to_archive }}"
      register: archive

    - name: "Download archive from {{ files.source }}"
      ansible.builtin.get_url:
        url: "{{ files.source }}"
        dest: "{{ path_to_archive }}"
      retries: 3
      delay: 5
      register: archive_download
      when:
        - archive.stat is defined
        - not archive.stat.exists

    - ansible.builtin.stat:
        path: "{{ files.home }}"
      register: path_to_home

    - ansible.builtin.stat:
        path: "{{ files.home }}/{{ files.name }}"
      register: path_to_home

    - name: "Unpack archive {{ path_to_archive }} to {{ files.home }}"
      ansible.builtin.unarchive:
        src: "{{ path_to_archive }}"
        dest: "{{ files.home }}"
        remote_src: yes
      when:
        - path_to_home is defined
        - path_to_home.stat is defined
        - not path_to_home.stat.exists
