---
- ansible.builtin.assert:
    that:
      - jdk_home_folder is defined
      - mvn_home_folder is defined

- name: "Ensures the tools home folder exits."
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ jdk_home_folder }}"
    - "{{ mvn_home_folder }}"

- name: "Install JDK versions"
  ansible.builtin.include_tasks: install_and_default.yml
  vars:
    home_folder: "{{ jdk_home_folder }}"
    list: "{{ jdk_list }}"
    tool_default: "{{ jdk_default }}"
    tool_default_link: "{{ jdk_default_link }}"
  when:
    - jdk_list is defined

- name: "Install maven versions"
  ansible.builtin.include_tasks: install_and_default.yml
  vars:
    home_folder: "{{ mvn_home_folder }}"
    list: "{{ mvn_list }}"
    tool_default: "{{ mvn_default }}"
    tool_default_link: "{{ mvn_default_link }}"
  when:
    - mvn_list is defined
