---
- assert:
    that:
      - home_folder is defined
      - home_folder != ""
      - list is defined
      - list is iterable
    quiet: true

- name: "Ensures the home dir exits: {{ home_folder }}"
  ansible.builtin.file:
    state: directory
    path: "{{ home_folder }}"

- ansible.builtin.include_tasks: tasks/java_tools_setup.yml
  loop: "{{ list }}"

- name: "Symlink {{ default_link }} to default version {{ default_version }}"
  ansible.builtin.file:
    src: "{{ default_version  }}"
    dest: "{{  default_link }}"
    state: link
  when:
    - default_link is defined
    - default_version is defined
