---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:

    - name: "Include common prepare tasks"
      ansible.builtin.include_tasks: ../prepare.yml

    - name: "Check that path to motd file has been defined"
      ansible.builtin.assert:
        that:
          - motd_path is defined
        quiet: true

    - name: "Load metadata on {{ motd_path }}"
      ansible.builtin.stat:
        path: "{{ motd_path }}"
      register: file_details

    - name: "Ensure that {{ motd_path }} exists."
      ansible.builtin.assert:
        that:
          - file_details is defined
          - file_details.stat is defined
          - file_details.stat.exists
        quiet: true
        fail_msg: "{{ motd_path }} does not exists."
