---
- name: Verify for motd role
  hosts: all
  vars_files:
    - vars.yml
  gather_facts: yes
  tasks:
    - name: Add a duplicate motd
      ansible.builtin.copy:
        src: "../../roles/motd/files/motd.standard"
        dest: /etc/duplicateMotd
        owner: root
        group: root
        mode: 0644

    - name: Get checksum of my original file
      ansible.builtin.stat:
        path: "{{ motd_path }}"
      register: originalfile

    - ansible.builtin.set_fact:
        original: "{{ originalfile.stat.checksum }}"

    - name: Get checksum of my duplicate file
      ansible.builtin.stat:
        path: "/etc/duplicateMotd"
      register: duplicatefile

    - ansible.builtin.set_fact:
        duplicate: "{{ duplicatefile.stat.checksum }}"

    - name: Compare both the files
      ansible.builtin.debug:
        msg: "File Compare"
      failed_when: original != duplicate

    - name: Verify that motd role was properly executed
      ansible.builtin.assert:
        that: true

