---
- name: Verify for motd role
  hosts: all
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
    # TODO: Ranabir :)
    - name: Verify that motd role was properly executed
      assert:
        that: true

