- name: "Ensure {{ tools.package_name }} is installed"
  ansible.builtin.include_role:
    name: fast_yum_install
  vars:
    package_name: "{{ files }}"
  with_items: "{{ tools.package_names }}"
  loop_control:
    loop_var: files
