---
# defaults file for zeus_cronjobs
logs_cleaning:
  name: 'cleaning-eap-server-logs'
  root_folder: '/opt/rh/eap7/root/usr/share/wildfly/standalone/log'
  nb_days_oldest: 31
  filename_pattern: 'server*.log.20*'
cronjobs:
  - { name: "Ansible Daily Report", template: templates/cron-ansible.j2, dest: /root/cron-ansible, frequency: daily, job: /root/cron-ansible  }
  - { name: "Monit Weekly Report", template: templates/cron-monit.j2, dest: /root/cron-monit, frequency: weekly, job: /root/cron-monit }
  - { name: "Cleaning logfiles", template: templates/cron-cleaning-logs.j2, dest: /root/cron-cleaning-logs, frequency: daily, job: /root/cron-cleaning-logs } 
fixed_time_cronjobs:
- { name: "Delete all forgotten ws-cleanup directories", minute: 0, hour: 10, weekday: 0, job: "/root/cron-cleaning-ws-cleanup-directories.sh >> /var/log/ws-cleanup.log", script: files/cron-cleaning-ws-cleanup-directories.sh, dest: /root/cron-cleaning-ws-cleanup-directories }

