---
- name: Prepare
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Add the user jenkins
      ansible.builtin.user:
        name: jenkins

    - name: Creates directory
      become: yes
      ansible.builtin.file:
        path: /opt/tools
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0644

    - name: "Deploy aphrodite configuration to {{ aphrodite.path }}"
      ansible.builtin.template:
        src: "../../roles/aphrodite/templates/aphrodite.json.j2"
        dest: "{{ aphrodite.path }}"
        owner: jenkins
        group: jenkins
        mode: 0644
