---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:

    - name: "Include common prepare tasks"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        users:
          - "{{ aphrodite_user }}"
        dirs:
          - { path: /opt/tools, owner: "{{ aphrodite_user }}", group: "{{ aphrodite_user }}" }

    - name: "Deploy aphrodite configuration to {{ aphrodite.path }}"
      become: yes
      ansible.builtin.template:
        src: "../../roles/aphrodite/templates/aphrodite.json.j2"
        dest: "{{ aphrodite.path }}"
        owner: "{{ aphrodite_user }}"
        group: "{{ aphrodite_user }}"
        mode: 0644
