---
- ansible.builtin.assert:
    that:
      - ares is defined
      - ares.home is defined
      - ares.home != ""
      - ares.git is defined
      - ares.git.repo is defined
      - ares.git.branch is defined
      - ares.git.keyfile is defined
    quiet: true

- ansible.builtin.stat:
    path: "{{ ares.git.keyfile }}"
  register: github_keyfile_path

- assert:
    that:
      - github_keyfile_path is defined
      - github_keyfile_path.stat is defined
      - github_keyfile_path.stat.exists
    quiet: true

- name: "Fetch images definition from {{ ares.git.repo }} from branch {{ ares.git.branch }}."
  ansible.builtin.git:
    repo: "{{ ares.git.repo }}"
    dest: "{{ ares.home }}"
    version: "{{ ares.git.branch }}"
    key_file: "{{ ares.git.keyfile }}"

- name: "Ensure {{ ares.home }} belongs to {{ ares.owner }}"
  ansible.builtin.file:
    path: "{{ ares.home }}"
    recurse: yes
    owner: "{{ ares.owner }}"
    group: "{{ ares.group }}"
  changed_when: false # weirdly this task always ends up in changed=true

- name: "Add redhat.repo to images that needs to use host's subs"
  ansible.builtin.copy:
    src: /etc/yum.repos.d/redhat.repo
    remote_src: yes
    dest: "{{ ares.home }}/{{ images }}"
    owner: "{{ ares.owner }}"
    group: "{{ ares.group }}"
  with_items: "{{ ares.images_with_subs }}"
  loop_control:
    loop_var: images
  when:
    - not ansible_check_mode
    - ares.images_with_subs is defined
    - ares.images_with_subs | length > 0

- name: "Add {{ ares.owner }} SSH key to containers that requires it"
  ansible.builtin.file:
    src: "/home/{{ ares.owner }}/.ssh/id_rsa.pub"
    dest: '{{ ares.home }}/{{ keys }}'
    state: hard
  with_items: "{{ ares.images_with_sshkey }}"
  loop_control:
    loop_var: keys
  when:
    - ares.images_with_sshkey is defined
    - ares.images_with_sshkey | length > 0
