---
- ansible.builtin.assert:
    that:
      - private_key is defined
      - private_key != ""
      - cert is defined
      - cert != ""
      - csr is defined
      - csr != ""
      - domain_name is defined
      - domain_name != ""
    quiet: true

# fails if not a path ?
- ansible.builtin.stat:
    path: "{{ files }}"
  with_items:
    - private_key
    - cert
  loop_control:
    loop_var: files

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ private_key }}"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ csr }}"
    privatekey_path: "{{ private_key }}"
    common_name: "{{ domain_name }}"

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ cert }}"
    privatekey_path: "{{ private_key }}"
    csr_path: "{{ csr }}"
    provider: selfsigned

