---
- include_role:
    name: podman

- name: "Running the payload_status container"
  containers.podman.podman_container:
    name: yarn-builder-container
    image: localhost/yarn-builder:latest
    volume: "{{ payload_status.home }}:/workspace:rw"
    state: started
    detach: no
    command: "./build.sh"
  become: yes
  become_user: "{{ payload_status.owner }}"

- ansible.builtin.set_fact:
    build_dir: "{{ payload_status.home }}/build"

- ansible.builtin.stat:
    path: "{{ build_dir }}"
  register: path_to_build_dir

- ansible.builtin.debug:
    msg: "{{ path_to_build_dir }}"

- ansible.builtin.assert:
    that:
      - path_to_build_dir is defined
      - path_to_build_dir.stat is defined
      - path_to_build_dir.stat.exists
    quiet: true

- name: "Ensure symlink to nginx_http_docroot is set"
  ansible.builtin.file:
    state: link
    src: "{{ payload_status.home }}"
    dest: "{{ nginx_http_docroot }}/payload_status }}"
    owner: "{{ nginx_username }}"
    group: "{{ nginx_groupname }}"
  when:
    - path_to_build_dir.stat.exists
    - nginx is defined
    - nginx_http_docroot is defined
    - nginx_username is defined

