---
- name: Prepare
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "Install sudo if user is root"
      ansible.builtin.yum:
        name: sudo
        state: present
      when:
        - ansible_user_id == "root"

    - name: Creates directory
      become: yes
      ansible.builtin.file:
        path: /root/.ansible/roles/infosec.qualys-cloud-agent/tasks/
        state: directory
        mode: 0644
