---
- block:
  - name: Add Ansible inventory mappings to /etc/hosts
    become: true
    ansible.builtin.blockinfile:
      path: "{{ hosts_path_to_file }}"
      block: |
        {% for host in hosts %}
        {{ host.ip }} {{ host.names }}
        {% endfor %}
  when:
    - hosts is defined
    - hosts is iterable
    - hosts | length > 0
