---
podman:
  home: "{{ podman_home | default('/opt/podman') }}"
  packages:
    - slirp4netns
    - podman
    - podman-docker
  kernel:
    max_user_namespaces: 28633
    user_namespaces_config_file: /etc/sysctl.d/userns.conf
  images:
    remotes:
      - { name: 'docker.io/library/nginx' }
    locals:
      - { name: 'automatons', owner: 'jenkins', tag: 'automatons' }
      - { name: 'bashomatons', owner: 'jenkins', tag: 'bashomatons' }
      - { name: 'yarn-builder', owner: 'jenkins', tag: 'yarn-builder' }
      - { name: 'hephaestus', owner: 'root', tag: 'hephaestus' }
      - { name: 'hephaestus', owner: 'root', tag: 'hephaestus.next' }
      - { name: 'ansible', owner: 'jenkins', tag: 'ansible' }
      - { name: 'janus', owner: 'jenkins', tag: 'janus' }
      - { name: 'molecule-runner-9', owner: 'jenkins', tag: 'molecule-runner-9' }
      - { name: 'molecule-slave-9', owner: 'jenkins', tag: 'molecule-slave-9' }
