---
- name: "Replace content of Windows specific tasks, that are not Ansible 2.21 compliant"
  ansible.builtin.template:
    dest: "{{ tasks }}"
    src: templates/dummy.j2
  with_items:
    - '/root/.ansible/roles/infosec.qualys-cloud-agent/tasks/setup-Windows.yml'
    - '/root/.ansible/roles/infosec.qualys-cloud-agent/tasks/uninstall-Windows.yml'
  loop_control:
    loop_var: tasks

