---        
name: CI   
           
on:        
  pull_request:
  push:    
    branches:
      - olympus
           
jobs:      
  test:    
    name: molecule
    runs-on: ubuntu-latest
           
    steps: 
      - name: Checkout the codebase.
        uses: actions/checkout@v2
           
      - name: Set up Python3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
           
      - name: Install testing dependencies.
        run: |
          pip install --upgrade pip
          pip install molecule
          pip install docker
          pip install podman
          pip install --user "molecule[podman,lint]"
          pip install --user "molecule[docker,lint]"
           
      - name: "Run molecule tests: motd"
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: rhel-8               
        working-directory: 'roles/motd'

      - name: "Run molecule tests: java"
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: rhel-8
        working-directory: 'roles/java'

      - name: "Run molecule tests: java_certs"
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: rhel-8
        working-directory: 'roles/java_certs'
