---        
name: CI   
           
on:        
  pull_request:
  push:    
    branches:
      - main
           
jobs:      
  test:    
    name: molecule
    runs-on: ubuntu-latest
           
    steps: 
      - name: Checkout the codebase.
        uses: actions/checkout@v2
           
      - name: Set up Python3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
           
      - name: Install testing dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule>=4.0.4' 'molecule-plugins[podman]>=23.0.0' ansible-core flake8 ansible-lint voluptuous
          ansible-galaxy collection install -r requirements.yml

      - name: Run linter
        run: |
          ansible-lint --version
          ansible-lint -v

      - name: "Run molecule tests"
        run: molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: rhel-8               
        working-directory: '.'
